In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('..')

In [3]:
import numpy as np

In [4]:
from src import vectorize
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
%aimport -sys
%aimport -MultinomialNB
%aimport -BernoulliNB
%aimport -GaussianNB
%aimport -classification_report
%aimport -np

In [5]:
target_names = ['PERIOD', 'QMARK', 'EXPOINT']

In [6]:
X, y = vectorize.tokens_to_bag_of_words('../data/processed/merged_tok.txt', one_hot_y=False)
X_bern, y_bern = vectorize.tokens_to_binary('../data/processed/merged_tok.txt', one_hot_y=False)

In [7]:
train, dev, test = vectorize.train_dev_test_split(X, y, 0.05, 0.05)
train_bern, dev_bern, test_bern = vectorize.train_dev_test_split(X_bern, y_bern, 0.05, 0.05)

In [23]:
x_test, y_test = test
y_test = np.ravel(y_test)
x_test_bern, y_test_bern = test_bern
y_test_bern = np.ravel(y_test_bern)

In [8]:
x_train, y_train = train
y_train = y_train.ravel()
clf_mult = MultinomialNB()
clf_mult.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [14]:
x_dev, y_dev = dev
y_dev = np.ravel(y_dev)
y_pred = clf_mult.predict(x_dev)
print(classification_report(y_dev, y_pred, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.84      0.99      0.91      1942
       QMARK       0.60      0.15      0.24       198
     EXPOINT       0.70      0.09      0.16       230

   micro avg       0.83      0.83      0.83      2370
   macro avg       0.71      0.41      0.43      2370
weighted avg       0.80      0.83      0.78      2370



In [15]:
print(classification_report(y_dev, np.zeros_like(y_dev).astype(int), target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.82      1.00      0.90      1942
       QMARK       0.00      0.00      0.00       198
     EXPOINT       0.00      0.00      0.00       230

   micro avg       0.82      0.82      0.82      2370
   macro avg       0.27      0.33      0.30      2370
weighted avg       0.67      0.82      0.74      2370



/Users/ericmarkmartin/.virtualenvs/cs229-autumn-2018-project-3R6jIYo2/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
print(classification_report(y_test, np.zeros_like(y_test).astype(int), target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.82      1.00      0.90      1932
       QMARK       0.00      0.00      0.00       198
     EXPOINT       0.00      0.00      0.00       240

   micro avg       0.82      0.82      0.82      2370
   macro avg       0.27      0.33      0.30      2370
weighted avg       0.66      0.82      0.73      2370



In [18]:
x_train_bern, y_train_bern = train_bern
y_train_bern = y_train_bern.ravel()
clf_bern = BernoulliNB()
clf_bern.fit(x_train_bern, y_train_bern)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [21]:
x_dev_bern, y_dev_bern = dev_bern
y_pred_bern = clf_bern.predict(x_dev_bern)
print(classification_report(y_dev_bern.ravel(), y_pred_bern, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.91      0.82      0.86      1942
       QMARK       0.48      0.22      0.30       198
     EXPOINT       0.29      0.67      0.40       230

   micro avg       0.75      0.75      0.75      2370
   macro avg       0.56      0.57      0.52      2370
weighted avg       0.81      0.75      0.77      2370



In [30]:
y_pred_test_bern = clf_bern.predict(x_test_bern)
print(classification_report(y_test_bern, y_pred_test_bern, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.92      0.83      0.87      1932
       QMARK       0.64      0.24      0.35       198
     EXPOINT       0.30      0.68      0.42       240

   micro avg       0.77      0.77      0.77      2370
   macro avg       0.62      0.58      0.54      2370
weighted avg       0.83      0.77      0.78      2370



In [31]:
confusion_matrix(y_test_bern, y_pred_test_bern)

array([[1606,   23,  303],
       [  76,   47,   75],
       [  73,    4,  163]])

In [28]:
confusion_matrix(y_dev_bern, y_pred_bern)

array([[1588,   44,  310],
       [  86,   43,   69],
       [  74,    3,  153]])

In [17]:
clf_bern_2 = BernoulliNB()
clf_bern_2.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [18]:
y_pred_bern_2 = clf_bern_2.predict(x_dev)
print(classification_report(y_dev, y_pred_bern_2, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.91      0.82      0.86      1942
       QMARK       0.48      0.22      0.30       198
     EXPOINT       0.29      0.67      0.40       230

   micro avg       0.75      0.75      0.75      2370
   macro avg       0.56      0.57      0.52      2370
weighted avg       0.81      0.75      0.77      2370



In [19]:
clf_g = GaussianNB()
clf_g.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [20]:
y_pred_g = clf_g.predict(x_dev)
print(classification_report(y_dev, y_pred_g, target_names=target_names))
print(confusion_matrix(y_dev, y_pred_g))

              precision    recall  f1-score   support

      PERIOD       0.92      0.50      0.65      1942
       QMARK       0.14      0.63      0.22       198
     EXPOINT       0.18      0.31      0.23       230

   micro avg       0.49      0.49      0.49      2370
   macro avg       0.41      0.48      0.37      2370
weighted avg       0.78      0.49      0.57      2370

[[977 668 297]
 [ 40 124  34]
 [ 42 116  72]]


In [21]:
confusion_matrix(y_dev, y_pred_g)

array([[977, 668, 297],
       [ 40, 124,  34],
       [ 42, 116,  72]])

In [22]:
confusion_matrix(y_dev, np.zeros_like(y_dev, dtype=int))

array([[1942,    0,    0],
       [ 198,    0,    0],
       [ 230,    0,    0]])

In [23]:
confusion_matrix(y_dev, y_pred)

array([[1918,   17,    7],
       [ 167,   29,    2],
       [ 207,    2,   21]])

In [24]:
confusion_matrix(y_dev, y_pred_bern_2)

array([[1589,   43,  310],
       [  86,   43,   69],
       [  74,    3,  153]])

In [25]:
clf2 = MultinomialNB()
clf2.fit(x_train_bern, y_train_bern)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [26]:
y_pred_2 = clf2.predict(x_dev_bern)
print(classification_report(y_dev_bern, y_pred_2, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.84      0.99      0.91      1942
       QMARK       0.66      0.14      0.23       198
     EXPOINT       0.72      0.08      0.14       230

   micro avg       0.83      0.83      0.83      2370
   macro avg       0.74      0.40      0.42      2370
weighted avg       0.81      0.83      0.78      2370



In [27]:
confusion_matrix(y_dev_bern, y_pred_2)

array([[1925,   12,    5],
       [ 169,   27,    2],
       [ 210,    2,   18]])

In [31]:
from sklearn.model_selection import GridSearchCV
parameters = {'tfidf__use_idf': (True, False),
              'tfidf__smooth_idf': (True, False),
              'tfidf__sublinear_tf': (True, False),
              'clf__alpha': (1, 1e-1, 1e-2, 1e-3)}

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer

In [34]:
mult_nb_tf = Pipeline([
    ('tfidf', TfidfTransformer()),
    ('clf', MultinomialNB())
])

In [35]:
grid_cv = GridSearchCV(mult_nb_tf, parameters, n_jobs=-1)

In [36]:
grid_cv.fit(x_train, y_train)

/Users/ericmarkmartin/.virtualenvs/cs229-autumn-2018-project-3R6jIYo2/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [38]:
mult_nb_tf.fit(x_train, y_train)

Pipeline(memory=None,
     steps=[('tfidf', TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [39]:
y_tf_pred = mult_nb_tf.predict(x_dev)

In [40]:
np.mean(y_tf_pred == y_dev)

0.8169652299311008

In [42]:
print(classification_report(y_dev, y_tf_pred, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.82      1.00      0.90      1942
       QMARK       1.00      0.01      0.01       198
     EXPOINT       1.00      0.03      0.06       230

   micro avg       0.82      0.82      0.82      2370
   macro avg       0.94      0.35      0.32      2370
weighted avg       0.85      0.82      0.75      2370



In [43]:
confusion_matrix(y_dev, y_tf_pred)

array([[1942,    0,    0],
       [ 197,    1,    0],
       [ 223,    0,    7]])

In [ ]:
clf_bern_2 = BernoulliNB(alpha=1e-4)
clf_bern_2.fit(x_train_bern, y_train_bern)

y_pred_bern_2 = clf_bern_2.predict(x_dev_bern)
print(classification_report(y_dev_bern, y_pred_bern, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.91      0.82      0.86      1942
       QMARK       0.48      0.22      0.30       198
     EXPOINT       0.29      0.67      0.40       230

   micro avg       0.75      0.75      0.75      2370
   macro avg       0.56      0.57      0.52      2370
weighted avg       0.81      0.75      0.77      2370



In [ ]:
confusion_matrix(y_dev_bern, y_pred_bern)