In [2]:
import sys
sys.path.append('..')

In [3]:
from src import vectorize

In [22]:
from sklearn.svm import SVC 
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import SGDClassifier
import numpy as np

In [4]:
target_names = ['PERIOD', 'QMARK', 'EXPOINT']

In [5]:
X, y = vectorize.tokens_to_bag_of_words('../data/processed/merged_tok.txt', one_hot_y=False)

In [6]:
train, dev, test = vectorize.train_dev_test_split(X, y, 0.05, 0.05)

In [16]:
x_train, y_train = train
y_train = y_train.ravel()

x_dev, y_dev = dev
y_dev = y_dev.ravel()

x_test, y_test = test
y_test = y_test.ravel()

In [ ]:
clf = SVC(gamma='auto')
clf.fit(x_train, y_train)

In [ ]:
y_pred = clf.predict(x_dev)

In [ ]:
print(classification_report(y_dev.ravel(), y_pred, target_names=target_names))

In [ ]:
clf_poly = SVC(gamma='auto', kernel='linear')
clf_poly.fit(x_train, y_train)

In [ ]:
y_pred_poly = clf_poly.predict(x_dev)

In [ ]:
print(classification_report(y_dev.ravel(), y_pred_poly, target_names=target_names))

In [42]:
np.count_nonzero(y_pred)

0

In [40]:
import numpy as np

In [43]:
len(y_pred)

42653

In [45]:
len(x_dev)

42653

In [46]:
len(x_train)

2369

In [28]:
sgd = SGDClassifier(random_state=229)

In [29]:
sgd.fit(x_train, y_train)

/Users/ericmarkmartin/.virtualenvs/cs229-autumn-2018-project-3R6jIYo2/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=None,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=229, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False)

In [39]:
y_pred = sgd.predict(x_dev)

In [40]:
print(classification_report(y_dev, y_pred, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.85      0.99      0.91      1942
       QMARK       0.66      0.28      0.40       198
     EXPOINT       0.61      0.10      0.17       230

   micro avg       0.84      0.84      0.84      2370
   macro avg       0.71      0.46      0.49      2370
weighted avg       0.81      0.84      0.80      2370



In [41]:
confusion_matrix(y_dev, y_pred)

array([[1913,   18,   11],
       [ 138,   56,    4],
       [ 196,   11,   23]])

In [33]:
y_pred_test = sgd.predict(x_test)

In [34]:
print(classification_report(y_test, y_pred_test, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.86      0.98      0.92      1932
       QMARK       0.68      0.35      0.46       198
     EXPOINT       0.76      0.17      0.28       240

   micro avg       0.85      0.85      0.85      2370
   macro avg       0.77      0.50      0.55      2370
weighted avg       0.83      0.85      0.82      2370



In [35]:
confusion_matrix(y_test, y_pred_test)

array([[1903,   17,   12],
       [ 128,   69,    1],
       [ 182,   16,   42]])

In [26]:
rnd_idx = np.random.choice(np.arange(len(x_train)), size=4000)

In [27]:
clf = SVC(gamma='auto')
clf.fit(x_train[rnd_idx], y_train[rnd_idx])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [36]:
y_svc_pred = clf.predict(x_dev)

In [37]:
print(classification_report(y_dev, y_svc_pred, target_names=target_names))

              precision    recall  f1-score   support

      PERIOD       0.82      1.00      0.90      1942
       QMARK       0.00      0.00      0.00       198
     EXPOINT       0.00      0.00      0.00       230

   micro avg       0.82      0.82      0.82      2370
   macro avg       0.27      0.33      0.30      2370
weighted avg       0.67      0.82      0.74      2370



/Users/ericmarkmartin/.virtualenvs/cs229-autumn-2018-project-3R6jIYo2/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [38]:
confusion_matrix(y_dev, y_svc_pred)

array([[1942,    0,    0],
       [ 198,    0,    0],
       [ 230,    0,    0]])